theme = "catppuccin_macchiato"

[editor]
bufferline = "always"
color-modes = true
cursorline = true
line-number = "relative"
mouse = false
rulers = [81]
end-of-line-diagnostics = "hint"
path-completion = false

[editor.inline-diagnostics]
cursor-line = "error"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "•"
render = true
skip-levels = 1

[editor.lsp]
auto-signature-help = false

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "position-percentage", "file-encoding"]

[keys.normal]
C-j = ["page_down", "goto_window_center"]
C-k = ["page_up", "goto_window_center"]
C-s = [":w"]
C-space = ["signature_help"]
C-g = [":sh kitty @ launch --type tab --tab-title git --cwd current --no-response && kitty @ send-text --match-tab title:git lazygit\\\\n"]
"ret" = "goto_word"

[keys.insert]
C-s = [":w"]
C-space = ["signature_help"]

