[language-server.angular]
command = "ngserver"
args = ["--stdio", "--tsProbeLocations", "/home/jbaker/.local/share/pnpm/global/5/node_modules", "--ngProbeLocations", "/home/jbaker/.local/share/pnpm/global/5/node_modules"]

[language-server.vscode-eslint-language-server]
command = "vscode-eslint-language-server"
args = ["--stdio"]

[language-server.vscode-eslint-language-server.config]
validate = "on"
experimental = { useFlatConfig = true }
rulesCustomizations = []
run = "onType"
problems = { shortenToSingleLine = false }
nodePath = ""

[language-server.vscode-eslint-language-server.config.codeAction.disableRuleComment]
enable = true
location = "separateLine"

[language-server.vscode-eslint-language-server.config.codeAction.showDocumentation]
enable = true

[language-server.vscode-eslint-language-server.config.workingDirectory]
mode = "location"

[[language]]
name = "typescript"
roots = ["angular.json", "project.json"]
language-servers = ["angular", "vscode-eslint-language-server", { name = "typescript-language-server", except-features = ["format"] }]
formatter = { command = "prettier", args = ["--write", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = ["vscode-eslint-language-server", { name = "typescript-language-server", except-features = ["format"] }]
formatter = { command = "prettier", args = ["--write", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "json"
language-servers = [{ name = "vscode-json-language-server", except-features = ["format"] }]
formatter = { command = "prettier", args = ["--write", "--parser", "json"] }
auto-format = true

[[language]]
name = "html"
roots = ["angular.json", "project.json"]
language-servers = ["angular", { name = "vscode-html-language-server", except-features = ["format"] }]
formatter = { command = "prettier", args = ["--write", "--parser", "angular"] }
auto-format = true

[[language]]
name = "css"
language-servers = ["biome", { name = "vscode-css-language-server", except-features = ["format"] }]
formatter = { command = "prettier", args = ["--write", "--parser", "css"] }
auto-format = true

[[language]]
name = "scss"
language-servers = [{ name = "vscode-css-language-server", except-features = ["format"] }]
formatter = { command = "prettier", args = ["--write", "--parser", "scss"] }
auto-format = true

[[language]]
name = "yaml"
formatter = { command = "prettier", args = ["--write", "--parser", "yaml"] }
auto-format = true

[[language]]
name = "markdown"
formatter = { command = "prettier", args = ["--write", "--parser", "markdown"] }
auto-format = true
