git:
  diffContextSize: 5
  forcePushStrategy: "ForceWithLease"
gui:
  nerdFontsVersion: "3"
  showBottomLine: true
  showFileTree: true
  sidePanelWidth: 0.333
  theme:
    activeBorderColor:
      - "#8bd5ca"
      - bold
    inactiveBorderColor:
      - "#a5adcb"
    optionsTextColor:
      - "#8aadf4"
    selectedLineBgColor:
      - "#363a4f"
    cherryPickedCommitBgColor:
      - "#494d64"
    cherryPickedCommitFgColor:
      - "#8bd5ca"
    unstagedChangesColor:
      - "#ed8796"
    defaultFgColor:
      - "#cad3f5"
    searchingActiveBorderColor:
      - "#eed49f"
  authorColors:
    "*": "#b7bdf8"
quitOnTopLevelReturn: true
